# Introduction to Matrices in Python Using Numpy

In [1]:
import numpy as np
import random

In [6]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M
# print(M)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# two by two matrix with random numbers
T = np.random.randint(-2,3, size=(2,2))
T

array([[ 2, -2],
       [ 2,  2]])

## Particular Matrices

* **Identity Matrix**

In [13]:
# Identity matrix 3x3
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* **Zero matrix**

In [16]:
# zeros wants tuples
Z = np.zeros((3,3))
Z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

* **Ones matrix**

In [17]:
O = np.ones((5,4))
O

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

* **Diagonal matrix**

In [18]:
D = np.diag([1,2,3])
D

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [19]:
C = np.diag(M)
C

array([1, 5, 9])