# Introduction to Linear Algebra Functions in Python

In [1]:
import numpy as np
import random
#from numpy.linalg import multidot

In [3]:
# Given the following matrices and vectors
M = np.linspace(-8,8,9).reshape(3,3)
N = np.random.randint(-8,8, size=(3,3))
O = 2*N
v1 = np.array([1,3,5,7])
v2 = np.array([2,4,6,8])
v3 = np.array([-2,5,1,3])


### The dot() function does the product of either two matrices, or two vectors

In [5]:
N.dot(M)

array([[ 32.,  42.,  52.],
       [ 88.,  66.,  44.],
       [ -4., -12., -20.]])

In [6]:
v1.dot(v2)

100

### The multidot function returns the product of two or several matrices

In [7]:
np.linalg.multi_dot([M,N,O])

array([[ -660.,  -768.,  1392.],
       [   36.,     0.,   108.],
       [  732.,   768., -1176.]])

### The vdot() function returns the product of two vectors. It does not perform a matrix multiplication. It should only be used for vectors

In [8]:
np.vdot(v1,v2)

100

### The inner() function returns the inner product of two arrays

In [9]:
np.inner(v3,v1)

39

### The matmul() function returns the product of two matrices

In [10]:
np.matmul(M,N)

array([[ 54.,  48., -60.],
       [  0.,   0., -18.],
       [-54., -48.,  24.]])

### The linalg.matrix_power(M,n) raises the square matrix M to the power of n

In [17]:
np.linalg.matrix_power(M,2)

array([[ 60.,  24., -12.],
       [ 24.,  24.,  24.],
       [-12.,  24.,  60.]])

### The linalg.eig(O) returns both the eigenvalues and eigenvectors of the matrix O

In [21]:
eig_vals, eig_vects = np.linalg.eig(O)
print(eig_vals)
print(" ")
print(eig_vects)

[-16.+0.j          -4.+4.47213595j  -4.-4.47213595j]
 
[[ 0.        +0.j          0.52365208+0.32017389j  0.52365208-0.32017389j]
 [ 1.        +0.j         -0.74865883+0.j         -0.74865883-0.j        ]
 [ 0.        +0.j         -0.20659711+0.14179129j -0.20659711-0.14179129j]]


### The linalg.eig(N) returns both the eigenvalues and eigenvectors of a complex Hermitian matrix or a real symmetric matrix N

In [22]:
eigh_vals, eigh_vects = np.linalg.eigh(N)
print(eigh_vals)
print(" ")
print(eigh_vects)

[-12.35592639  -3.08299843   3.43892481]
 
[[ 0.52749391 -0.08214645  0.84557799]
 [ 0.8476859   0.11694631 -0.51744775]
 [ 0.05638072 -0.98973508 -0.13132285]]


### The linalg.det(N) returns the determinant of the matrix N

In [16]:
np.linalg.det(N)

-72.0

### The linalg.inv(N) returns the invers of the matrix N

In [15]:
np.linalg.inv(N)

array([[-0.33333333, -0.        , -0.66666667],
       [ 0.34722222, -0.125     ,  0.52777778],
       [ 0.11111111, -0.        , -0.11111111]])